# Generated by Django 2.0.9 on 2018-10-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20181017_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credit_card_no',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
