# Generated by Django 2.0.9 on 2018-10-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paymentDetails',
            new_name='user_details',
        ),
    ]
