# Generated by Django 2.0.9 on 2018-10-30 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20181025_1955'),
        ('conference_manager', '0003_auto_20181025_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respaper', to='author.ResearchPaper'),
        ),
    ]
