# Generated by Django 2.0.9 on 2018-10-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_manager', '0004_track_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='paper_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
