# Generated by Django 2.0.9 on 2018-10-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20181025_2151'),
        ('conference_manager', '0005_track_paper_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respaper', to='reviewer.ReviewReport'),
        ),
    ]
