# Generated by Django 2.0.9 on 2018-11-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_manager', '0008_track_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='report_approved',
        ),
        migrations.AddField(
            model_name='track',
            name='permission_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='track_approved',
            field=models.BooleanField(default=False),
        ),
    ]
