# Generated by Django 2.0.9 on 2018-11-21 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference_manager', '0009_auto_20181117_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.TextField(blank=True, null=True)),
                ('conference_date', models.DateField()),
                ('conference_chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_chair', to=settings.AUTH_USER_MODEL)),
                ('conference_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceTypes',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Workshop'), (2, 'Seminar'), (3, 'Conference')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='conference_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conference_manager.ConferenceTypes'),
        ),
    ]
