# Generated by Django 2.0.9 on 2018-11-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference_manager', '0010_auto_20181121_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conference_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference_manager.ConferenceTypes'),
        ),
    ]
