# Generated by Django 2.0.9 on 2018-11-26 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference_manager', '0011_auto_20181121_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='registration_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
