# Generated by Django 2.0.9 on 2018-10-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Very good'), (2, 'Good'), (3, 'Average'), (4, 'Below Average'), (5, 'Bad')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('lit_review', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lr_perf', to='reviewer.Performance')),
                ('methodology', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_perf', to='reviewer.Performance')),
                ('problem_statement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ps_perf', to='reviewer.Performance')),
                ('research_sig', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rs_perf', to='reviewer.Performance')),
            ],
        ),
    ]
