# Generated by Django 2.0.9 on 2018-10-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreport',
            name='lit_review',
            field=models.CharField(choices=[('VERYGOOD', 'Very good'), ('GOOD', 'Good'), ('AVERAGE', 'Average'), ('BELOWAVG', 'Below Average'), ('BAD', 'Bad')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='methodology',
            field=models.CharField(choices=[('VERYGOOD', 'Very good'), ('GOOD', 'Good'), ('AVERAGE', 'Average'), ('BELOWAVG', 'Below Average'), ('BAD', 'Bad')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='problem_statement',
            field=models.CharField(choices=[('VERYGOOD', 'Very good'), ('GOOD', 'Good'), ('AVERAGE', 'Average'), ('BELOWAVG', 'Below Average'), ('BAD', 'Bad')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='research_sig',
            field=models.CharField(choices=[('VERYGOOD', 'Very good'), ('GOOD', 'Good'), ('AVERAGE', 'Average'), ('BELOWAVG', 'Below Average'), ('BAD', 'Bad')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
