# Generated by Django 2.0.9 on 2018-11-21 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20181025_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreport',
            name='days_left',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='submission_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
