# Generated by Django 2.1.2 on 2018-10-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('authors', models.CharField(max_length=100, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Abstract'), (2, 'Full Proposal'), (3, 'Both')])),
                ('docfile', models.FileField(null=True, upload_to='research_papers')),
            ],
        ),
        migrations.DeleteModel(
            name='PostAd',
        ),
    ]
