# Generated by Django 2.0.9 on 2018-11-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20181025_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='days_left',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='submission_date',
            field=models.DateField(null=True),
        ),
    ]
