# Generated by Django 2.0.9 on 2018-11-21 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20181121_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='submission_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
