# Generated by Django 2.0.9 on 2018-10-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20181022_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='id',
        ),
    ]
