# Generated by Django 2.1.2 on 2018-11-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20181022_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='validated',
            field=models.BooleanField(null=True),
        ),
    ]
