# Generated by Django 2.0.9 on 2018-10-25 10:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_no', models.CharField(max_length=20)),
                ('cvv', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(default=datetime.datetime(2018, 10, 25, 15, 58, 49, 987329), verbose_name='expiration date')),
                ('amount', models.IntegerField(default=200)),
                ('payment_date', models.DateTimeField(verbose_name='Date paid')),
                ('started', models.BooleanField(default=False)),
                ('ongoing', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
