# Generated by Django 2.0.9 on 2018-10-25 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 25, 18, 4, 43, 243679), verbose_name='expiration date'),
        ),
    ]
