# Generated by Django 2.0.9 on 2018-10-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_auto_20181025_1831'),
        ('payment_app', '0003_auto_20181025_1830'),
    ]

    operations = [
    ]
