# Generated by Django 2.1.2 on 2018-10-25 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0005_auto_20181025_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 25, 19, 57, 13, 394861), verbose_name='expiration date'),
        ),
    ]
