# Generated by Django 2.0.9 on 2018-10-25 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0005_auto_20181025_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 25, 21, 51, 50, 463869), verbose_name='expiration date'),
        ),
    ]
