# Generated by Django 2.0.9 on 2018-10-25 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0006_auto_20181025_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 26, 0, 31, 59, 657588), verbose_name='expiration date'),
        ),
    ]
