# Generated by Django 2.1.2 on 2018-10-25 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0006_auto_20181025_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 25, 19, 58, 26, 778116), verbose_name='expiration date'),
        ),
    ]
