# Generated by Django 2.1.2 on 2018-10-25 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0007_auto_20181025_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 26, 0, 6, 50, 516272), verbose_name='expiration date'),
        ),
    ]
