# Generated by Django 2.0.9 on 2018-10-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0007_auto_20181025_1958'),
        ('payment_app', '0007_auto_20181026_0031'),
    ]

    operations = [
    ]
