# Generated by Django 2.0.9 on 2018-10-30 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0009_auto_20181030_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 30, 16, 57, 24, 51219), verbose_name='expiration date'),
        ),
    ]
