# Generated by Django 2.0.9 on 2018-10-30 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0012_auto_20181030_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 30, 18, 13, 44, 641160), verbose_name='expiration date'),
        ),
    ]
