# Generated by Django 2.0.9 on 2018-11-09 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0013_auto_20181030_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 9, 15, 37, 16, 350656), verbose_name='expiration date'),
        ),
    ]
