# Generated by Django 2.1.2 on 2018-11-17 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0013_auto_20181030_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 19, 10, 51, 900416), verbose_name='expiration date'),
        ),
    ]
