# Generated by Django 2.0.9 on 2018-11-09 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0014_auto_20181109_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 9, 16, 8, 27, 913275), verbose_name='expiration date'),
        ),
    ]
