# Generated by Django 2.0.9 on 2018-11-13 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0015_auto_20181109_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 13, 19, 53, 37, 653281), verbose_name='expiration date'),
        ),
    ]
