# Generated by Django 2.1.2 on 2018-11-17 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0015_auto_20181117_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 19, 31, 10, 305614), verbose_name='expiration date'),
        ),
    ]
