# Generated by Django 2.0.9 on 2018-11-13 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0016_auto_20181113_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 13, 20, 3, 42, 746645), verbose_name='expiration date'),
        ),
    ]
