# Generated by Django 2.0.9 on 2018-11-25 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0017_auto_20181113_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 11, 26, 4, 699058), verbose_name='expiration date'),
        ),
    ]
