# Generated by Django 2.0.9 on 2018-11-25 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0018_auto_20181125_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 15, 24, 47, 507033), verbose_name='expiration date'),
        ),
    ]
