# Generated by Django 2.0.9 on 2018-11-25 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0019_auto_20181125_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 15, 29, 4, 215355), verbose_name='expiration date'),
        ),
    ]
