# Generated by Django 2.0.9 on 2018-10-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_no', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=200)),
                ('user_details', models.CharField(max_length=200)),
                ('payment_date', models.DateTimeField(verbose_name='Date paid')),
                ('started', models.BooleanField(default=False)),
                ('ongoing', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
