# Generated by Django 2.0.9 on 2018-10-24 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_manager', '0002_auto_20181023_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 24, 20, 19, 52, 737661), verbose_name='expiration date'),
        ),
    ]
