# Generated by Django 2.0.9 on 2018-10-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_manager', '0003_auto_20181024_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
